queue_rules:
  - name: default
    merge_method: squash
    queue_conditions:
      - or:
        - author = jd
        - "#approved-reviews-by >= 1"
        - author = dependabot[bot]

merge_protections_settings:
  auto_merge_conditions:
    - or:
      - author = jd
      - "#approved-reviews-by >= 1"
      - author = dependabot[bot]

pull_request_rules:
  - name: dismiss reviews
    conditions: []
    actions:
      dismiss_reviews: {}
