queue_rules:
  - name: default
    merge_method: squash
    queue_conditions: &CheckRuns
      - "check-success=test (3.8, py38)"
      - "check-success=test (3.9, py39)"
      - "check-success=test (3.10, py310)"
      - "check-success=test (3.11, py311)"
      - "check-success=test (3.12, py312)"
      - "check-success=test (3.12, pep8)"

pull_request_rules:
  - name: warn on no changelog
    conditions:
      - -files~=^releasenotes/notes/
      - label!=no-changelog
      - -closed
    actions:
      comment:
        message: >
          ⚠️ No release notes detected. Please make sure to use
          [reno](https://docs.openstack.org/reno/latest/user/usage.html) to add
          a changelog entry.

  - name: automatic merge without changelog
    conditions:
      - or:
        - author=jd
        - author=dependabot
        - "#approved-reviews-by>=1"
      - or:
        - label=no-changelog
        - author=dependabot
    actions:
      queue:

  - name: automatic merge with changelog
    conditions:
      - or:
        - author=jd
        - "#approved-reviews-by>=1"
      - files~=^releasenotes/notes/
    actions:
      queue:

  - name: dismiss reviews
    conditions: []
    actions:
      dismiss_reviews: {}
