queue_rules:
  - name: default
    conditions: &CheckRuns
      - "check-success=test (3.6, py36)"
      - "check-success=test (3.7, py37)"
      - "check-success=test (3.8, py38)"
      - "check-success=test (3.9, py39)"
      - "check-success=test (3.10, py310)"
      - "check-success=test (3.11, py311)"
      - "check-success=test (3.11, black-ci)"
      - "check-success=test (3.11, pep8)"
      - "check-success=test (3.11, mypy)"

pull_request_rules:
  - name: warn on no changelog
    conditions:
      - -files~=^releasenotes/notes/
      - label!=no-changelog
      - -closed
    actions:
      comment:
        message: >
          ⚠️ No release notes detected. Please make sure to use
          [reno](https://docs.openstack.org/reno/latest/user/usage.html) to add
          a changelog entry.
  - name: automatic merge without changelog
    conditions:
      - and: *CheckRuns
      - "#approved-reviews-by>=1"
      - label=no-changelog
    actions:
      queue:
        name: default
        method: squash
  - name: automatic merge with changelog
    conditions:
      - and: *CheckRuns
      - "#approved-reviews-by>=1"
      - files~=^releasenotes/notes/
    actions:
      queue:
        name: default
        method: squash
  - name: automatic merge for jd without changelog
    conditions:
      - author=jd
      - and: *CheckRuns
      - label=no-changelog
    actions:
      queue:
        name: default
        method: squash
  - name: automatic merge for jd with changelog
    conditions:
      - author=jd
      - and: *CheckRuns
      - files~=^releasenotes/notes/
    actions:
      queue:
        name: default
        method: squash
  - name: dismiss reviews
    conditions: []
    actions:
      dismiss_reviews: {}
