pull_request_rules:
  - name: warn on no changelog
    conditions:
      - -files~=^releasenotes/notes/
      - label!=no-changelog
      - -closed
    actions:
      comment:
        message: >
          ⚠️ No release notes detected. Please make sure to use
          [reno](https://docs.openstack.org/reno/latest/user/usage.html) to add
          a changelog entry.
  - name: automatic merge without changelog
    conditions:
      - "status-success=ci/circleci: pep8"
      - "status-success=ci/circleci: black"
      - "status-success=ci/circleci: mypy"
      - "status-success=ci/circleci: py36"
      - "status-success=ci/circleci: py37"
      - "status-success=ci/circleci: py38"
      - "status-success=ci/circleci: py39"
      - "#approved-reviews-by>=1"
      - label=no-changelog
    actions:
      merge:
        strict: "smart"
        method: squash
  - name: automatic merge with changelog
    conditions:
      - "status-success=ci/circleci: pep8"
      - "status-success=ci/circleci: black"
      - "status-success=ci/circleci: mypy"
      - "status-success=ci/circleci: py36"
      - "status-success=ci/circleci: py37"
      - "status-success=ci/circleci: py38"
      - "status-success=ci/circleci: py39"
      - "#approved-reviews-by>=1"
      - files~=^releasenotes/notes/
    actions:
      merge:
        strict: "smart"
        method: squash
  - name: automatic merge for jd without changelog
    conditions:
      - author=jd
      - "status-success=ci/circleci: pep8"
      - "status-success=ci/circleci: black"
      - "status-success=ci/circleci: mypy"
      - "status-success=ci/circleci: py36"
      - "status-success=ci/circleci: py37"
      - "status-success=ci/circleci: py38"
      - "status-success=ci/circleci: py39"
      - label=no-changelog
    actions:
      merge:
        strict: "smart"
        method: squash
  - name: automatic merge for jd with changelog
    conditions:
      - author=jd
      - "status-success=ci/circleci: pep8"
      - "status-success=ci/circleci: black"
      - "status-success=ci/circleci: mypy"
      - "status-success=ci/circleci: py36"
      - "status-success=ci/circleci: py37"
      - "status-success=ci/circleci: py38"
      - "status-success=ci/circleci: py39"
      - files~=^releasenotes/notes/
    actions:
      merge:
        strict: "smart"
        method: squash
  - name: dismiss reviews
    conditions: []
    actions:
      dismiss_reviews: {}
